"""Add indexes for performance

Revision ID: acde808800d5
Revises: c52569414936
Create Date: 2026-08-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acde808800d5'
down_revision: Union[str, Sequence[str], None] = 'c52569414936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_incidents_status', 'incidents', ['status'])
    op.create_index('ix_incidents_severity', 'incidents', ['severity'])
    op.create_index('ix_incidents_classification', 'incidents', ['classification'])
    op.create_index('ix_recoveries_state', 'recoveries', ['state'])
    op.create_index('ix_policy_decisions_decision', 'policy_decisions', ['decision'])
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_event_type', table_name='audit_events')
    op.drop_index('ix_policy_decisions_decision', table_name='policy_decisions')
    op.drop_index('ix_recoveries_state', table_name='recoveries')
    op.drop_index('ix_incidents_classification', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    # ### end Alembic commands ###