"""Add foreign key constraints

Revision ID: c52569414936
Revises: 6a5c247d56f9
Create Date: 2026-08-22 22:40:37.222884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c52569414936'
down_revision: Union[str, Sequence[str], None] = '6a5c247d56f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'incidents', 'merchants', ['merchant_id'], ['id'])
    op.create_foreign_key(None, 'evidence_packages', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'forensic_reports', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'policy_decisions', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'recoveries', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'audit_events', 'incidents', ['incident_id'], ['id'])
    op.create_foreign_key(None, 'audit_events', 'recoveries', ['recovery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'recoveries', type_='foreignkey')
    op.drop_constraint(None, 'policy_decisions', type_='foreignkey')
    op.drop_constraint(None, 'forensic_reports', type_='foreignkey')
    op.drop_constraint(None, 'evidence_packages', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    # ### end Alembic commands ###
